In [22]:
# Initial imports
import pandas as pd
import numpy as np
from path import Path
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression # logestic reg is a linear model also linear regression is another ex of a linear model

In [23]:
np.random.seed(42)

In [2]:
Xs =[]
ys = []
cmlabel = []

all_features_org= ['age', 'avg_glucose_level', 'bmi', 'hypertension', 'heart_disease',
       'gender_Female', 'gender_Male', 'gender_Other', 'ever_married_No',
       'ever_married_Yes', 'work_type_Govt_job', 'work_type_Never_worked',
       'work_type_Private', 'work_type_Self-employed', 'work_type_children',
       'Residence_type_Rural', 'Residence_type_Urban',
       'smoking_status_Unknown', 'smoking_status_formerly smoked',
       'smoking_status_never smoked', 'smoking_status_smokes']

all_features= ['age', 'avg_glucose_level', 'bmi', 'hypertension_0', 'hypertension_1', 'heart_disease_0', 'heart_disease_1',
       'gender_Female', 'gender_Male', 'gender_Other', 'ever_married_No',
       'ever_married_Yes', 'work_type_Govt_job', 'work_type_Never_worked',
       'work_type_Private', 'work_type_Self-employed', 'work_type_children',
       'Residence_type_Rural', 'Residence_type_Urban',
       'smoking_status_Unknown', 'smoking_status_formerly smoked',
       'smoking_status_never smoked', 'smoking_status_smokes']
lifestyle_features=['bmi',
       'ever_married_No',
       'ever_married_Yes', 'work_type_Govt_job', 'work_type_Never_worked',
       'work_type_Private', 'work_type_Self-employed', 'work_type_children',
       'Residence_type_Rural', 'Residence_type_Urban',
       'smoking_status_Unknown', 'smoking_status_formerly smoked',
       'smoking_status_never smoked', 'smoking_status_smokes']
medical_features=['age', 'avg_glucose_level', 'hypertension', 'heart_disease',
       'gender_Female', 'gender_Male', 'gender_Other']


my_features= ['age', 'avg_glucose_level', 'bmi','hypertension_0', 'hypertension_1', 'heart_disease_0', 'heart_disease_1',
        'ever_married_No',
       'ever_married_Yes', 'work_type_Govt_job', 'work_type_Never_worked',
       'work_type_Private', 'work_type_Self-employed', 'work_type_children',
       'smoking_status_Unknown', 'smoking_status_formerly smoked',
       'smoking_status_never smoked', 'smoking_status_smokes']

features=all_features_org

#root_path="Resources/backup_files/"
root_path="Resources/"

In [4]:
# Loading testing data
file_path = Path(root_path+"stroke_testing_data.csv")
df_testing = pd.read_csv(file_path)

X_test=df_testing[features]
y_test=df_testing["stroke"]

df_testing

,age,avg_glucose_level,bmi,hypertension,heart_disease,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,...,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0.877930,0.221827,0.203182,0,0,1,0,0,0,1,...,0,1,0,1,0,0,1,0,0,0
1,0.548340,0.433817,0.283966,0,0,1,0,0,0,1,...,0,1,0,1,0,1,0,0,0,0
2,0.890137,0.074219,0.335373,1,0,0,1,0,1,0,...,0,0,0,0,1,0,0,1,0,0
3,0.450684,0.211759,0.197062,0,0,1,0,0,0,1,...,1,0,0,1,0,1,0,0,0,0
4,0.572754,0.093340,0.319461,0,0,1,0,0,0,1,...,1,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223,0.353027,0.040089,0.429621,0,0,1,0,0,0,1,...,1,0,0,0,1,0,0,0,1,0
1224,0.572754,0.011731,0.280294,0,0,0,1,0,0,1,...,1,0,0,1,0,0,0,0,1,0
1225,0.890137,0.307639,0.244798,0,0,0,1,0,0,1,...,1,0,0,1,0,0,1,0,0,0
1226,0.768066,0.232311,0.337821,0,0,0,1,0,0,1,...,1,0,0,0,1,0,1,0,0,0
1227,0.157715,0.204461,0.160343,0,0,1,0,0,1,0,...,0,0,1,1,0,1,0,0,0,0

In [5]:
# Loading data
file_path = Path(root_path+"stroke_training_ActualDataSample.csv")
df_actsample = pd.read_csv(file_path)

Xs.append(df_actsample[features])
ys.append(df_actsample["stroke"])
cmlabel.append("Using ActualDataSample")

df_actsample

,age,avg_glucose_level,bmi,hypertension,heart_disease,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,...,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0.019043,0.125947,0.058752,0,0,1,0,0,1,0,...,0,0,1,1,0,1,0,0,0,0
1,0.951172,0.628626,0.173807,1,0,1,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
2,0.511719,0.037179,0.204406,0,0,1,0,0,1,0,...,1,0,0,0,1,0,0,1,0,0
3,0.536133,0.131027,0.168911,1,0,0,1,0,0,1,...,0,1,0,1,0,0,0,1,0,0
4,0.609375,0.697534,0.527540,0,0,1,0,0,0,1,...,1,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,0.975586,0.042583,0.424725,0,0,1,0,0,0,1,...,1,0,0,0,1,0,0,1,0,1
362,0.987793,0.604979,0.228886,0,0,0,1,0,0,1,...,1,0,0,0,1,0,1,0,0,1
363,0.816895,0.801173,0.321909,0,1,0,1,0,0,1,...,1,0,0,0,1,0,1,0,0,1
364,0.829102,0.778727,0.264382,0,1,0,1,0,0,1,...,1,0,0,0,1,0,1,0,0,1
365,0.951172,0.015472,0.170135,0,0,1,0,0,0,1,...,1,0,0,0,1,1,0,0,0,1

In [6]:
# Loading data
file_path = Path(root_path+"stroke_training_randomoversampled.csv")
df_rdmnsampl = pd.read_csv(file_path)

Xs.append(df_rdmnsampl[features])
ys.append(df_rdmnsampl["stroke"].values)
cmlabel.append("Using Random Oversampling")

df_rdmnsampl

,age,avg_glucose_level,bmi,hypertension,heart_disease,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,...,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0.206543,0.158692,0.152999,0,0,1,0,0,1,0,...,1,0,0,0,1,1,0,0,0,0
1,0.487305,0.412248,0.238678,0,0,0,1,0,0,1,...,1,0,0,1,0,0,0,0,1,0
2,0.658203,0.143359,0.303550,0,0,0,1,0,0,1,...,1,0,0,0,1,0,1,0,0,0
3,0.560547,0.284593,0.219094,0,0,1,0,0,0,1,...,1,0,0,1,0,0,0,1,0,0
4,0.938965,0.076113,0.275398,1,0,1,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7043,0.914551,0.766996,0.189718,1,0,0,1,0,0,1,...,1,0,0,0,1,0,0,0,1,1
7044,0.975586,0.061472,0.170135,0,1,0,1,0,0,1,...,1,0,0,0,1,0,0,0,1,1
7045,0.658203,0.227646,0.208078,0,0,1,0,0,0,1,...,1,0,0,0,1,0,0,0,1,1
7046,0.768066,0.379087,0.261934,0,0,0,1,0,0,1,...,1,0,0,1,0,0,1,0,0,1
7047,0.975586,0.084611,0.167687,0,0,1,0,0,0,1,...,1,0,0,0,1,1,0,0,0,1

In [7]:
# Loading data
file_path = Path(root_path+"stroke_training_SMOTEENN.csv")
df_smoteensmpl = pd.read_csv(file_path)

Xs.append(df_smoteensmpl[features])
ys.append(df_smoteensmpl["stroke"])
cmlabel.append("Using SMOTEENN Sampling")

df_smoteensmpl

,age,avg_glucose_level,bmi,hypertension,heart_disease,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,...,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0.206543,0.158692,0.152999,0,0,1,0,0,1,0,...,1,0,0,0,1,1,0,0,0,0
1,0.487305,0.412248,0.238678,0,0,0,1,0,0,1,...,1,0,0,1,0,0,0,0,1,0
2,0.560547,0.284593,0.219094,0,0,1,0,0,0,1,...,1,0,0,1,0,0,0,1,0,0
3,0.938965,0.076113,0.275398,1,0,1,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
4,0.145508,0.054683,0.070991,0,0,0,1,0,1,0,...,0,0,1,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6233,0.811222,0.852950,0.369496,0,0,1,0,0,0,1,...,1,0,0,0,1,0,1,0,0,1
6234,0.592245,0.320831,0.259396,0,0,0,1,0,0,1,...,1,0,0,1,0,0,0,1,0,1
6235,0.956760,0.193550,0.227334,1,0,1,0,0,0,1,...,0,1,0,0,1,0,0,0,0,1
6236,0.973036,0.639875,0.226351,0,0,0,1,0,0,1,...,0,0,0,0,1,0,1,0,0,1
6237,0.784818,0.609516,0.330100,0,0,0,1,0,0,1,...,1,0,0,0,1,0,0,0,1,1

In [48]:
def train_test_logistic(X_train, y_train, X_test, y_test, label):

    ## Creating the decision tree classifier instance
    global logic_re
    logic_re = LogisticRegression(penalty='l2', solver='sag', max_iter=100)
    # Fitting the model
    logic_re = logic_re.fit(X_train, y_train)
    # Making predictions using the testing data
    predictions = logic_re.predict(X_test)
    
    # Calculating the confusion matrix
    cm = confusion_matrix(y_test, predictions)
    cm_df = pd.DataFrame(
        cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
    )

    # Calculating the accuracy score
    acc_score = accuracy_score(y_test, predictions)
    
    # Displaying results
    print("Logistic Regression")
    print(f"Confusion Matrix:{label}")
    display(cm_df)
    print(f"Accuracy Score : {acc_score}")
    print("Classification Report")
    print(classification_report(y_test, predictions))

In [49]:
for i, _ in enumerate(ys):
    X_train = Xs[i]
    y_train= ys[i]
    label= cmlabel[i]
    train_test_logistic(X_train, y_train, X_test, y_test, label)

Logistic Regression
Confusion Matrix:Using ActualDataSample

          Predicted 0  Predicted 1
Actual 0          919          257
Actual 1           14           38

Accuracy Score : 0.7793159609120521
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.78      0.87      1176
           1       0.13      0.73      0.22        52

    accuracy                           0.78      1228
   macro avg       0.56      0.76      0.55      1228
weighted avg       0.95      0.78      0.84      1228

Logistic Regression
Confusion Matrix:Using Random Oversampling

          Predicted 0  Predicted 1
Actual 0          867          309
Actual 1           13           39

Accuracy Score : 0.737785016286645
Classification Report
              precision    recall  f1-score   support

           0       0.99      0.74      0.84      1176
           1       0.11      0.75      0.20        52

    accuracy                           0.74      1228
   macro avg       0.55      0.74      0.52      1228
weighted avg       0.95      0.74      0.82      1228

Logistic Regression
Confusion Matrix:Using SMOTEENN Sampling

          Predicted 0  Predicted 1
Actual 0          931          245
Actual 1           21           31

Accuracy Score : 0.7833876221498371
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.79      0.88      1176
           1       0.11      0.60      0.19        52

    accuracy                           0.78      1228
   macro avg       0.55      0.69      0.53      1228
weighted avg       0.94      0.78      0.85      1228

In [50]:
X_train = Xs[0]
y_train= ys[0]
label= cmlabel[0]
train_test_logistic(X_train, y_train, X_test, y_test, label)

Logistic Regression
Confusion Matrix:Using ActualDataSample

          Predicted 0  Predicted 1
Actual 0          919          257
Actual 1           14           38

Accuracy Score : 0.7793159609120521
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.78      0.87      1176
           1       0.13      0.73      0.22        52

    accuracy                           0.78      1228
   macro avg       0.56      0.76      0.55      1228
weighted avg       0.95      0.78      0.84      1228

In [51]:
import pickle
import joblib

In [52]:
def save_model(model_name, model):
    '''
    model_name = name.pkl
    joblib.load('name.pkl')
    assign a variable to load model
    '''
    with open(str(model_name), 'wb') as f:
        pickle.dump(model, f)

In [53]:
save_model("LogReg.pkl", logic_re)

In [54]:
model = joblib.load("LogReg.pkl")